:toc: left
:toclevels: 5
:sectnums:
:stem:
:source-highlighter: coderay

# 配置

## システムアーキテクチャ

[plantuml]
----
@startuml
actor 開発者
actor 利用者

cloud "AWS" as aws {
    package "Production Environment" as api_prd_env {
      [APP] as app_prd
      [DB] as db_prd
    }
}

cloud "GitHub" as github {
  package "Repository" as repository {
    [Git] as git
  }

  package "Continuous Integration" as ci {
    [GiHubAction] as github_action
  }
}

開発者 --> repository
repository --> aws
app_prd -> db_prd
git -> github_action
app_prd <-- 利用者
@enduml
----

これは、ソフトウェア開発と展開の高レベルの概要を示すUMLダイアグラムです。開発者、本番環境、およびリポジトリの3つの主要なコンポーネントが示されています。

開発者はアクターによって表され、利用者のアクターもあり、ダイアグラム上では「利用者」と表記されています。

本番環境には、Webアプリケーションを展開するためのプラットフォームであるAWSクラウドがあります。本番環境は、「Production Environment」のアプリケーションとデータベースを含むパッケージで構成されています。

リポジトリは、Gitバージョン管理システム「Git Hub」と継続的インテグレーションシステムの「GitHub Action」という2つのパッケージを含むGitHubクラウドで表されています。

このダイアグラムは、開発者がコードをリポジトリにプッシュすることで、GitHub Actionを使用した継続的インテグレーションプロセスがトリガーされることを示しています。継続的インテグレーションプロセスは、コードをビルドしてテストし、AWSの本番環境の両方に展開します。

最終的に、利用者はAWSを介してアプリケーションとやり取りし、本番環境のAPIとデータベースコンポーネントと通信します。

## GitHubとは
GitHubは、GitリポジトリをホストするためのWebベースのホスティングサービスです。GitHubを使用すると、コードを共有し、他の人と協力してプロジェクトを管理できます。

### GitHubのセットアップ
. [GitHub](https://github.com/)にアクセスして、アカウントを作成します。
. リポジトリを作成します。
. リポジトリにコードをプッシュします。

## GitHub Actionsとは
GitHub Actionsは、GitHubでホストされる継続的インテグレーション/継続的デプロイメント（CI/CD）サービスです。GitHub Actionsを使用すると、コードの変更を自動的にビルド、テスト、デプロイできます。

### GitHub Actionsのセットアップ
. リポジトリに `.github/workflows` ディレクトリを作成します。
. ワークフローファイルを作成します。
+
`node.js.yml` を作成します。
+
[source,yml]
----
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
----
+
. レポジトリにコミット・プッシュしてワークフローを有効にします。
+
. READMEにバッジを追加します。

## AWSとは

AWS（Amazon Web Services）は、Amazon.comが提供するクラウドコンピューティングプラットフォームです。AWSは、コンピューティング、ストレージ、データベース、分析、ネットワーキング、モバイル、開発ツール、マネジメントツール、IoT、セキュリティ、アプリケーションサービスなど、さまざまなサービスを提供しています。

### AWSにアプリをデプロイする手順
#### AWS アカウントの作成

#### AWS CLI のインストール

#### アプリケーションの作成

#### アプリケーションのデプロイ

#### アプリケーションの起動
